name: Build

on:
  push:

env:
  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/latest/download/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
  TOOLCHAIN_DIR: /opt/arm-webos-linux-gnueabi_sdk-buildroot
  TOOLCHAIN_FILE: /opt/arm-webos-linux-gnueabi_sdk-buildroot/share/buildroot/toolchainfile.cmake

jobs:
  build-native-component:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download and unpack toolchain
      working-directory: /opt
      run: |
        wget -q -O toolchain.tar.gz ${TOOLCHAIN_URL}
        tar xf toolchain.tar.gz

    - name: Relocate toolchain
      working-directory: ${{ env.TOOLCHAIN_DIR }}
      run: |
        ./relocate-sdk.sh

    - name: CMake Version
      run: cmake --version

    - name: Create Build directory
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Build component
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE .. && make

    - name: List files
      run: find .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperion_webos
        path: |
          ${{github.workspace}}/build/hyperion-webos
          ${{github.workspace}}/build/libdile_vt_backend.so
          ${{github.workspace}}/build/libvt_backend.so
          ${{github.workspace}}/build/libvtcapture_backend.so